branchName: '${issue.number}-${issue.title}'
branches:
  - label: 'âœ¨ Feature'
    prefix: feat/
  - label: 'ğŸ”¨ Refactor'
    prefix: refactor/
  - label: 'âœ… Test'
    prefix: test/
  - label: 'ğŸ“ƒ Docs'
    prefix: docs/
  - label: 'âš™ Setting'
    prefix: setting/
  - label: 'ğŸŒ Deploy'
    prefix: deploy/
  - label: 'ğŸ¨ Design'
    prefix: design/
  - label: 'ğŸ BugFix'
    prefix: bugfix/
  - label: 'ğŸ“¬ API'
    prefix: api/
  - label: 'ğŸ™‹â€â™‚ï¸ Question'
    prefix: question/
autoCloseIssue: true
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
